env:
    KT_LINK: "https://github.com/johnmart19/Redline_kernel_onclite"
    KT_BRANCH: "ThinLTO_4.14_backports"
    TG_TOKEN: "ENCRYPTED[ba114ab260e16ec1509fdf7feb928222ac87f272d56a7a28ec884582cfe8106d49a7840098af770b34c41d75a618f602]"
    TG_CHAT_ID: "ENCRYPTED[e829773cf31c517e0ebc9f80aa4fba71d062fed3db2193ac7701593971a8ef83626e1f8e8aa69c7471b7943db4d8a082]"
    TZ: "Asia/Kolkata"

task:
  name: "Kernel-Builder"
  timeout_in: 480m  
  container:
      image: marvelmathesh/docker:rom
      cpu: 8
      memory: 16G

  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive
       - mkdir -p /tmp/ccache
       - cd /tmp

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h

  Build_script:
      - bash kernel.sh
